version: "3.3"

services:
    mmdet-serve:
        image: mlvulhub/mmdet-serve:latest
        ports:
            - 8080:8080
            - 8081:8081
            - 8082:8082
        volumes:
            - ./model-store:/home/model-server/model-store
        build:
            context: docker
            dockerfile: Dockerfile
            args:
                - PYTORCH=1.6.0
                - CUDA=10.1
                - CUDNN=7
                - MMCV=1.3.17
                - MMDET=2.25.2

volumes:
    model-store:
        external: false
