version: "3.3"

services:
    minio:
        image: quay.io/minio/minio:latest
        command: server /data --console-address ":9001"
        ports:
            - 9000:9000
            - 9001:9001
        volumes:
            - ./data:/data

volumes:
    data:
        external: false
